.\" (C) Copyright 2014 Emerick Bosch <xpc.dev@gmail.com>,
.TH PLOTUS 1 "September 16, 2014"
.SH NAME
PLOTUS - linear-programming plotting tool
.SH SYNOPSIS
.B plotus
.SH DESCRIPTION
.B Plotus
is a program that allows the user to input inequalities and to define
the variables which form these inequalities.
.br 
These inqualities are then evaluated and plotted against one another.
Results may be saved, loaded and combined.
.br 
The intention was to allow a quick tool for determining simple solution
spaces when modelling/characterizing a problem mathematically.
.SH OPTIONS
The interface theme is defined using Qt StyleSheets (a subset of CSS)
and can be modified by editing
.B default_theme.css.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.br 
.PP
The programs are documented fully by
Emerick Bosch
.IR  <xpc.dev@gmail.com>
